# Site settings
# in the templates available like {{ site.myvariable }}.
title: Portfolio
email: thinuss@gmail.com
brand: Thinus Snyman
headline: Engineer, Innovator and Software Enthusiast
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://snymanth.github.io" # the base hostname & protocol for your site
copyright: 2017 Thinus Snyman. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: thinuss@gmail.com
phone: +27-83-212-9376

# Tracking
googleAnalitycsID: UA-83933844-1


